spring:
  application:
    name: api-gateway
  messages:
    fallback-to-system-locale: false

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  structured:
    format:
      console: ecs

paseto:
  local-key: ${PASETO_LOCAL_KEY}

gateway:
  login-path: /api/v1/auth/login
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  bets-service-url: ${BETS_SERVICE_URL:http://localhost:8082}
  stats-service-url: ${STATS_SERVICE_URL:http://localhost:8083}
  service-key: ${SERVICE_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

---
spring:
  config:
    activate:
      on-profile: test

paseto:
  local-key: 93f681c1304df4c64f73a0df5c58c7eb097927246ad5b850247a97ef14774bc7

gateway:
  service-key: test-service-key
